name: Update Analytics Data

on:
  schedule:
    - cron: '0 * * * *'  # 매시 정각에 실행
  workflow_dispatch:      # 수동 실행 옵션 추가

jobs:
  update-analytics:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install @google-analytics/data
        
      - name: Update analytics data
        env:
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          GA4_PROPERTY_ID: ${{ secrets.GA4_PROPERTY_ID }}
        run: |
          echo "Checking environment variables..."
          if [ -n "$GOOGLE_CLIENT_EMAIL" ]; then
            echo "GOOGLE_CLIENT_EMAIL is set"
          else
            echo "GOOGLE_CLIENT_EMAIL is not set"
          fi
          node scripts/updateAnalytics.js
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add public/analytics-data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update analytics data" && git push)